"""add model UserActionORM

Revision ID: 2ee10f37d618
Revises: d6c3ac7235a6
Create Date: 2025-07-23 13:02:49.673432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee10f37d618'
down_revision: Union[str, None] = 'd6c3ac7235a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('user_tg_id', sa.BIGINT(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_action')
    # ### end Alembic commands ###
